version: '3.8'
services:
  backend:
    container_name: backend
    image: crccheck/hello-world
    
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend
    