version: '3.8'
services:
  backend:
    container_name: backend
    image: crccheck/hello-world

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email slima@elixir.co.mz -d lupa.co.mz --agree-tos 
    